##Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

##1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

##By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def sum(array)
	seq = array
	seq.pop
    sum = 0
    seq.each { |i|
        sum += i if i.even? }
    sum
end

array = [1,2]
	while array.last <= 4000000
		sums = array.last(2)
		array << sums[0] + sums[1]
    end
puts sum(array)
