#!/bin/bash

echo "Setting up Problem $1..."

FILE=problem_$1.rb

if [[ ! -a $FILE ]];
then
  touch $FILE
  touch spec/problem_$1_spec.rb
fi

touch tmp
TMP=tmp
curl -s http://projecteuler.net/problem\=$1 > tmp

cat $TMP | grep -e "\<h3\>" | sed 's/.*\<h3\>/\#/' | sed 's/\<\/h3\>.*//' >> $FILE
cat $TMP | grep -e "\<h2\>" | sed 's/\<h2\>/\#/' | sed 's/\<\/h2\>.*//' >> $FILE
rm $TMP

echo "require './problem_$1'" > spec/problem_$1_spec.rb
